
import React, { useState, useRef, useCallback } from 'react';
import VideoPlayer, { VideoPlayerHandle } from './components/VideoPlayer';
import SubtitleList from './components/SubtitleList';
import { VideoState, SubtitleNode, GenerationStatus } from './types';
import { PlayIcon, PauseIcon, UploadIcon, SparklesIcon, DownloadIcon, ImportIcon, GlobeIcon, FilmIcon } from './components/Icons';
import { generateSceneDescription, analyzeAudioDeeply, translateBatch } from './services/geminiService';
import { extractAudioFromVideo } from './utils/audioUtils';
import { detectScenes } from './utils/sceneDetection';

const App: React.FC = () => {
  const playerRef = useRef<VideoPlayerHandle>(null);
  const fileInputRef = useRef<HTMLInputElement>(null);
  const jsonInputRef = useRef<HTMLInputElement>(null);
  
  const [videoState, setVideoState] = useState<VideoState>({
    url: null,
    fileName: null,
    fileObj: null,
    duration: 0,
    currentTime: 0,
    isPlaying: false,
  });

  const [subtitles, setSubtitles] = useState<SubtitleNode[]>([]);
  const [genStatus, setGenStatus] = useState<GenerationStatus>(GenerationStatus.IDLE);
  const [progress, setProgress] = useState(0); // For visual scene detection progress
  const [isTranslating, setIsTranslating] = useState(false);

  // Handle Video File Upload
  const handleFileChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (file) {
      const url = URL.createObjectURL(file);
      setVideoState({
        url,
        fileName: file.name,
        fileObj: file,
        duration: 0,
        currentTime: 0,
        isPlaying: false,
      });
      setSubtitles([]); // Reset subtitles for new video
      setGenStatus(GenerationStatus.IDLE);
      setProgress(0);
    }
  };

  // Handle JSON Analysis Import
  const handleJsonUpload = (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (!file) return;

    const reader = new FileReader();
    reader.onload = (e) => {
      try {
        const content = e.target?.result as string;
        const parsedData = JSON.parse(content);
        
        if (Array.isArray(parsedData)) {
          setSubtitles(parsedData);
        } else {
          alert("Invalid JSON structure: Expected an array of subtitles.");
        }
      } catch (error) {
        console.error("Failed to parse JSON", error);
        alert("Failed to load JSON file. Please check the file format.");
      }
    };
    reader.readAsText(file);
    
    // Reset input so same file can be loaded again if needed
    if (jsonInputRef.current) {
      jsonInputRef.current.value = '';
    }
  };

  const handleTimeUpdate = useCallback((time: number) => {
    setVideoState(prev => ({ ...prev, currentTime: time }));
  }, []);

  const togglePlay = () => {
    if (videoState.isPlaying) {
      playerRef.current?.pause();
      setVideoState(prev => ({ ...prev, isPlaying: false }));
    } else {
      playerRef.current?.play();
      setVideoState(prev => ({ ...prev, isPlaying: true }));
    }
  };

  // 1. Quick Single Scene Analysis (Visual)
  const handleAnalyzeScene = async () => {
    if (genStatus !== GenerationStatus.IDLE || !playerRef.current) return;

    playerRef.current.pause();
    setVideoState(prev => ({ ...prev, isPlaying: false }));
    setGenStatus(GenerationStatus.ANALYZING_AI);

    const currentTimestamp = videoState.currentTime;

    try {
      const frameBase64 = playerRef.current.captureFrame();
      if (!frameBase64) throw new Error("Could not capture video frame.");

      const text = await generateSceneDescription(frameBase64);

      const newSubtitle: SubtitleNode = {
        id: crypto.randomUUID(),
        timestamp: currentTimestamp,
        text: text,
        isAutoGenerated: true,
        type: 'scene',
        thumbnail: frameBase64 // Use the captured frame as thumbnail
      };

      setSubtitles(prev => {
        const combined = [...prev, newSubtitle];
        return combined.sort((a, b) => a.timestamp - b.timestamp);
      });
      setGenStatus(GenerationStatus.SUCCESS);

    } catch (error) {
      console.error("Analysis failed", error);
      setGenStatus(GenerationStatus.ERROR);
    } finally {
      setTimeout(() => setGenStatus(GenerationStatus.IDLE), 2000);
    }
  };

  // 2. Full Deep Audio Analysis
  const handleFullAnalysis = async () => {
    if (!videoState.fileObj) return;
    
    setGenStatus(GenerationStatus.PROCESSING_AUDIO);
    playerRef.current?.pause();

    try {
      // Step 1: Extract Audio
      const audioBase64 = await extractAudioFromVideo(videoState.fileObj);
      
      setGenStatus(GenerationStatus.ANALYZING_AI);

      // Step 2: Send to Gemini
      const result = await analyzeAudioDeeply(audioBase64);
      
      // Step 3: Map Result
      const newNodes: SubtitleNode[] = result.segments.map((seg: any) => ({
        id: crypto.randomUUID(),
        timestamp: seg.startTime,
        endTime: seg.endTime,
        type: seg.type,
        text: seg.text,
        isAutoGenerated: true,
        speaker: seg.speaker,
        emotion: seg.emotion,
        musicAnalysis: seg.musicAnalysis
      }));

      // Append to existing (or merge if we were smarter, but append is fine for now)
      // Actually, let's sort them after adding
      setSubtitles(prev => {
        const combined = [...prev, ...newNodes];
        return combined.sort((a, b) => a.timestamp - b.timestamp);
      });
      
      setGenStatus(GenerationStatus.SUCCESS);

    } catch (error) {
      console.error("Deep Analysis Failed", error);
      setGenStatus(GenerationStatus.ERROR);
    } finally {
      setTimeout(() => setGenStatus(GenerationStatus.IDLE), 3000);
    }
  };

  // 3. Detect Visual Scenes (Client-Side Histogram Algo)
  const handleVisualSceneDetection = async () => {
    if (!videoState.fileObj || genStatus !== GenerationStatus.IDLE) return;

    playerRef.current?.pause();
    setGenStatus(GenerationStatus.PROCESSING_VIDEO);
    setProgress(0);

    try {
      // Call the optimized algorithm
      const scenes = await detectScenes(videoState.fileObj, (pct) => {
        setProgress(pct);
      });

      setSubtitles(prev => {
        const combined = [...prev, ...scenes];
        return combined.sort((a, b) => a.timestamp - b.timestamp);
      });
      setGenStatus(GenerationStatus.SUCCESS);
    } catch (error) {
      console.error("Visual Scene Detection Failed", error);
      setGenStatus(GenerationStatus.ERROR);
    } finally {
      setTimeout(() => {
        setGenStatus(GenerationStatus.IDLE);
        setProgress(0);
      }, 2000);
    }
  };

  // 4. Batch Translation
  const handleBatchTranslate = async (targetLang: 'Spanish' | 'English') => {
    if (subtitles.length === 0 || isTranslating) return;
    
    setIsTranslating(true);
    
    try {
      // Filter only dialogues or items with text that need translation
      const itemsToTranslate = subtitles; // Translate everything that has text
      const texts = itemsToTranslate.map(s => s.text);

      if (texts.length === 0) return;

      // Call Batch API
      const translatedTexts = await translateBatch(texts, targetLang);

      // Merge back into state
      setSubtitles(prev => {
        return prev.map((item, index) => {
          if (translatedTexts[index]) {
            return { ...item, translation: translatedTexts[index] };
          }
          return item;
        });
      });

    } catch (e) {
      console.error("Batch translation failed", e);
      alert("Batch translation failed. Try again.");
    } finally {
      setIsTranslating(false);
    }
  };

  const handleDeleteSubtitle = (id: string) => {
    setSubtitles(prev => prev.filter(s => s.id !== id));
  };

  const handleDownload = () => {
    if (subtitles.length === 0) return;

    const dataStr = JSON.stringify(subtitles, null, 2);
    const blob = new Blob([dataStr], { type: "application/json" });
    const url = URL.createObjectURL(blob);
    
    const link = document.createElement('a');
    link.href = url;
    const baseName = videoState.fileName ? videoState.fileName.split('.')[0] : 'scene_sync';
    link.download = `${baseName}_analysis.json`;
    
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const formatTime = (seconds: number) => {
    const min = Math.floor(seconds / 60);
    const sec = Math.floor(seconds % 60);
    return `${min}:${sec.toString().padStart(2, '0')}`;
  };

  return (
    <div className="flex flex-col h-screen bg-slate-950 text-slate-200 overflow-hidden font-sans selection:bg-blue-500/30">
      
      {/* Header */}
      <header className="h-16 border-b border-slate-800 flex items-center justify-between px-6 bg-slate-950/50 backdrop-blur-md z-10">
        <div className="flex items-center gap-2">
          <div className="w-8 h-8 bg-gradient-to-br from-blue-500 to-indigo-600 rounded-lg flex items-center justify-center shadow-lg shadow-blue-500/20">
            <span className="font-bold text-white text-lg">S</span>
          </div>
          <h1 className="font-semibold text-lg tracking-tight">SceneSync <span className="text-slate-500 font-normal">AI</span></h1>
        </div>

        <div className="flex items-center gap-4">
          <input
            type="file"
            accept="video/*"
            onChange={handleFileChange}
            ref={fileInputRef}
            className="hidden"
          />
          <button 
            onClick={() => fileInputRef.current?.click()}
            className="flex items-center gap-2 px-4 py-2 text-sm font-medium bg-slate-900 border border-slate-700 rounded-lg hover:bg-slate-800 hover:border-slate-600 transition-all"
          >
            <UploadIcon className="w-4 h-4" />
            {videoState.fileName ? 'Change Video' : 'Upload Video'}
          </button>
        </div>
      </header>

      {/* Main Workspace */}
      <main className="flex-1 flex overflow-hidden">
        
        {/* Left: Video Area */}
        <section className="flex-[2] flex flex-col p-6 gap-4 border-r border-slate-800 bg-slate-950 relative">
          
          <div className="flex-1 relative min-h-0">
             <VideoPlayer
                ref={playerRef}
                src={videoState.url}
                onTimeUpdate={handleTimeUpdate}
                onDurationChange={(dur) => setVideoState(prev => ({ ...prev, duration: dur }))}
                onEnded={() => setVideoState(prev => ({ ...prev, isPlaying: false }))}
              />
          </div>

          {/* Controls Bar */}
          <div className="h-20 bg-slate-900/50 border border-slate-800 rounded-xl flex items-center px-6 justify-between backdrop-blur-sm">
            <div className="flex items-center gap-4">
              <button 
                onClick={togglePlay}
                disabled={!videoState.url}
                className="w-10 h-10 flex items-center justify-center rounded-full bg-slate-200 text-slate-900 hover:bg-white disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
              >
                {videoState.isPlaying ? <PauseIcon /> : <PlayIcon className="ml-1" />}
              </button>
              <span className="font-mono text-sm text-slate-400">
                {formatTime(videoState.currentTime)} / {formatTime(videoState.duration)}
              </span>
            </div>

            <div className="flex gap-3">
              {/* 1. Visual Scene Detection */}
              <button
                onClick={handleVisualSceneDetection}
                disabled={!videoState.url || genStatus !== GenerationStatus.IDLE}
                className={`
                  flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-medium border transition-all disabled:opacity-50
                  ${genStatus === GenerationStatus.PROCESSING_VIDEO 
                    ? 'bg-orange-900/30 border-orange-500 text-orange-300' 
                    : 'text-slate-300 hover:bg-slate-800 border-transparent hover:border-slate-700'}
                `}
              >
                 {genStatus === GenerationStatus.PROCESSING_VIDEO ? (
                   <span className="flex items-center gap-2">
                     <svg className="animate-spin h-4 w-4" fill="none" viewBox="0 0 24 24"><circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle><path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path></svg>
                     {progress}%
                   </span>
                 ) : (
                    <>
                      <FilmIcon className="w-4 h-4" />
                      Detect Scenes
                    </>
                 )}
              </button>

              {/* 2. Single Snapshot */}
              <button
                onClick={handleAnalyzeScene}
                disabled={!videoState.url || genStatus !== GenerationStatus.IDLE}
                className="px-4 py-2 rounded-lg text-sm font-medium text-slate-300 hover:bg-slate-800 border border-transparent hover:border-slate-700 transition-all disabled:opacity-50"
              >
                Single Snapshot
              </button>

              {/* 3. Full Audio Analysis */}
              <button
                onClick={handleFullAnalysis}
                disabled={!videoState.url || genStatus !== GenerationStatus.IDLE}
                className={`
                  flex items-center gap-2 px-6 py-2.5 rounded-lg font-medium transition-all shadow-lg text-sm
                  ${genStatus !== GenerationStatus.IDLE && genStatus !== GenerationStatus.PROCESSING_VIDEO
                    ? 'bg-slate-800 text-slate-400 cursor-wait' 
                    : 'bg-gradient-to-r from-indigo-600 to-purple-600 hover:from-indigo-500 hover:to-purple-500 text-white shadow-indigo-500/25'
                  }
                `}
              >
                {genStatus === GenerationStatus.PROCESSING_AUDIO && (
                  <span className="animate-pulse">Extracting Audio...</span>
                )}
                {genStatus === GenerationStatus.ANALYZING_AI && (
                  <>
                     <svg className="animate-spin h-4 w-4 text-current" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                      <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                      <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                    </svg>
                    Analyzing AI...
                  </>
                )}
                {genStatus === GenerationStatus.SUCCESS && "Complete!"}
                {(genStatus === GenerationStatus.IDLE || genStatus === GenerationStatus.PROCESSING_VIDEO) && (
                  <>
                    <SparklesIcon className="w-4 h-4" />
                    Full Audio Analysis
                  </>
                )}
              </button>
            </div>
          </div>
        </section>

        {/* Right: Subtitles/Output */}
        <aside className="flex-1 bg-slate-900 border-l border-slate-800 flex flex-col min-w-[400px] max-w-[500px]">
          <div className="h-14 flex items-center justify-between px-5 border-b border-slate-800 bg-slate-900/80">
            <h2 className="font-medium text-slate-300">Analysis Results</h2>
            
            <div className="flex items-center gap-2">
              
              {/* Batch Translate */}
              <div className="flex items-center bg-slate-800 rounded-lg border border-slate-700 p-0.5 mr-2">
                 <div className="px-2 text-slate-500">
                   {isTranslating ? <svg className="animate-spin h-3 w-3" fill="none" viewBox="0 0 24 24"><circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle><path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path></svg> : <GlobeIcon className="w-3.5 h-3.5" />}
                 </div>
                 <button 
                   onClick={() => handleBatchTranslate('Spanish')}
                   disabled={subtitles.length === 0 || isTranslating}
                   className="px-2 py-1 text-[10px] font-bold text-slate-300 hover:bg-slate-700 hover:text-white rounded disabled:opacity-30"
                 >
                   ES
                 </button>
                 <div className="w-px h-3 bg-slate-700"></div>
                 <button 
                   onClick={() => handleBatchTranslate('English')}
                   disabled={subtitles.length === 0 || isTranslating}
                   className="px-2 py-1 text-[10px] font-bold text-slate-300 hover:bg-slate-700 hover:text-white rounded disabled:opacity-30"
                 >
                   EN
                 </button>
              </div>

               {/* Hidden JSON Input */}
               <input
                type="file"
                accept=".json"
                onChange={handleJsonUpload}
                ref={jsonInputRef}
                className="hidden"
              />
              
              <button
                onClick={() => jsonInputRef.current?.click()}
                className="p-2 text-slate-400 hover:text-white hover:bg-slate-800 rounded-lg transition-colors"
                title="Load JSON Results"
              >
                <ImportIcon className="w-4 h-4" />
              </button>

              <button
                onClick={handleDownload}
                disabled={subtitles.length === 0}
                className="p-2 text-slate-400 hover:text-white hover:bg-slate-800 rounded-lg transition-colors disabled:opacity-30 disabled:cursor-not-allowed"
                title="Download Results as JSON"
              >
                <DownloadIcon className="w-4 h-4" />
              </button>
            </div>
          </div>
          
          <div className="flex-1 overflow-hidden relative">
            <SubtitleList 
              subtitles={subtitles} 
              currentTime={videoState.currentTime}
              onJumpTo={(time) => {
                playerRef.current?.seekTo(time);
              }}
              onDelete={handleDeleteSubtitle}
            />
          </div>
        </aside>

      </main>
    </div>
  );
};

export default App;
