
export interface SubtitleNode {
  id: string;
  timestamp: number; // Start time
  endTime?: number;
  text: string;
  translation?: string; // New field for translated text
  thumbnail?: string; // New field for visual scene snapshot
  isAutoGenerated: boolean;
  type: 'dialogue' | 'music' | 'scene';
  
  // Dialogue specific
  speaker?: string;
  emotion?: string;
  
  // Music specific
  musicAnalysis?: MusicAnalysis;
}

export interface MusicAnalysis {
  source: 'Diegetic' | 'Non-Diegetic' | 'Silence/Ambient';
  tempo: 'Slow' | 'Medium' | 'Fast';
  dynamics: 'Low' | 'Medium' | 'High';
  progression: 'Crescendo' | 'Diminuendo' | 'Sustained';
  harmonicMode: 'Major' | 'Minor';
  sentimentScore: number; // -1.0 to 1.0
}

export interface VideoState {
  url: string | null;
  fileName: string | null;
  fileObj: File | null; // Added to store the raw file for audio extraction
  duration: number;
  currentTime: number;
  isPlaying: boolean;
}

export enum GenerationStatus {
  IDLE = 'IDLE',
  PROCESSING_VIDEO = 'PROCESSING_VIDEO',
  PROCESSING_AUDIO = 'PROCESSING_AUDIO',
  ANALYZING_AI = 'ANALYZING_AI',
  SUCCESS = 'SUCCESS',
  ERROR = 'ERROR'
}
